name: ğŸš€ Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: ğŸ”¬ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ”¬ Lint
        run: npm run lint

  typecheck:
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ” Type check
        run: npm run typecheck --if-present

  build:
    name: ğŸ”¨ Build
    # only build/deploy master branch on push (and closed merge request)
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    env:
      PORT: 5001
      AUTHPORT: 6000
      # DATABASE_URL ENV is set up in GitHub secrets for actions
      DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ”§ Build
        run: npm run build

  deploy:
    name:
      ğŸš€ Deploy
      # only build/deploy master branch on push (and closed merge request)
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build]
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: ğŸš€ Deploy Production to AWS Elastic Beanstalk
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          # Set this in github actions secrets
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # Set this in github actions secrets
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Change:
          application_name: remix-jokes-backend
          # Change:
          environment_name: remix-jokes-backend-env
          # Change:
          region: eu-west-1
          version_label: ${{ github.run_number }}
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo "Deployed Production to AWS Elastic Beanstalk ğŸš€ğŸš€ğŸš€"
